220906 sync 0.70 (#642)
* Add a few Microsoft apps to the showcase (#3203)

* fix artsy icon

* add microsoft office mobile

* add outlook mobile

* add teams

* add xbox

* remove placeholder link

* Correct minor mistake in native-components-android.md (#3210)

* Update fast-refresh.md (#3208)

Co-authored-by: Bartosz Kaszubowski <gosimek@gmail.com>

* Fixed Artsy logo and infoLink of oculus in webiste/showcase (#3199)

* Wrap "Android SDK Build-Tools" with backticks (#3206)

* Update keyboardavoidingview.md (#3202)

* Update debugging.md (#3209)

* Add the blogpost for Hermes as the Default engine (#3212)

* Add the blogpost for Hermes as the Default engine

* Update website/blog/2022-07-08-hermes-as-the-default.md

Co-authored-by: Bartosz Kaszubowski <gosimek@gmail.com>

* Update website/blog/2022-07-08-hermes-as-the-default.md

Co-authored-by: Bartosz Kaszubowski <gosimek@gmail.com>

Co-authored-by: Nicola Corti <corti.nico@gmail.com>
Co-authored-by: Bartosz Kaszubowski <gosimek@gmail.com>

* Update iOS data in Hermes default blog post (#3216)

* Update the contributing section docs (#3221)

Co-authored-by: Nicola Corti <corti.nico@gmail.com>
Co-authored-by: Bartosz Kaszubowski <gosimek@gmail.com>

* Bump terser from 5.12.1 to 5.14.2 (#3219)

Bumps [terser](https://github.com/terser/terser) from 5.12.1 to 5.14.2.
- [Release notes](https://github.com/terser/terser/releases)
- [Changelog](https://github.com/terser/terser/blob/master/CHANGELOG.md)
- [Commits](https://github.com/terser/terser/commits)

---
updated-dependencies:
- dependency-name: terser
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* docs: add build tools to Table of Contents (#3228)

* Update build-speed.md (#3223)

Removed duplicated sentence from docs

* Remove Uber Eats from showcase (#3229)

* docs: add two sections to the New Architecture (#3230)

* Note on connecting to React Native simulator. (#3214)

Co-authored-by: LeoTM <1881059+leotm@users.noreply.github.com>
Co-authored-by: Nicola Corti <corti.nico@gmail.com>

* Fix a couple of problems on the release runbook (#3222)

* Improving UX: replace videos and links with SnackPlayers, update examples (#3231)

* Fix extra whitespace on debugging.md (#3233)

* Add more info to Prerequisites for Libraries guide (#3238)

* Add spaces in the example

* Add section about codegen types

* Correct section title

* Add information about requireNativeComponent

* [Docs] iOS Simulator version & UDID (#3225)

Co-authored-by: Bartosz Kaszubowski <gosimek@gmail.com>

* Add retrospective as a copilot responsibility (#3242)

* update release related docs page (#3240)

* update crew composition and remove testers/supporters

* add note about testing async

* Update website/contributing/release-roles-responsibilites.md

Co-authored-by: Riccardo <riccardo.cipolleschi@gmail.com>

* Update website/contributing/release-roles-responsibilites.md

Co-authored-by: Riccardo <riccardo.cipolleschi@gmail.com>

* refactor note into a snipper

* Update website/contributing/release-roles-responsibilites.md

Co-authored-by: Marek Fořt <marekfort@me.com>

* yarnlock change?

* clean up document based on feedback

* more words at the start

Co-authored-by: Riccardo <riccardo.cipolleschi@gmail.com>
Co-authored-by: Marek Fořt <marekfort@me.com>

* Update image.md (#2850)

This is missing, but this is an important information. Imagine a view sized 100x150 and an image sized 200x300. The old description could be interpreted in a way, that the image doesn't scale at all!

* Fix lint

* chore: Specify return vs resolve (#3236)

When dealing with functions which return Promises, it's helpful to be clear about whether something _returns_ a value, or whether the returned Promise will _resolve to_ a value.

* update Docusaurus and other dependencies (#3218)

* Add kotlin examples in new-architecture-app-modules-android.md (#3241)

* change links in main home (#3244)

* Refactoring The New Architecture Guide (#3037)

* [Do Not Merge] Refactoring The New Architecture (#3029)

* [Guide - The New Architecture] What Backward Compatibility Is (#3038)

* Guide to creating a New Architecture app from template (#3056)

* Start new template guide

This is a first iteration. I want to get feedback on a few aspects, so
starting from here as a baseline.

* Update title

* Use tabs for target OS

Set up matching the style of "Getting Started", except I kept the
headers inside the tabs for now as it makes for a useful right-hand TOC.

* Capitalize New Architecture, simplify

* Preliminary section for Hermes

Add section for recommending enabling Hermes. Not sure of contents yet,
and still have to test.

* Reword to emphasize importance of Hermes usage

* Show new arch in use

* Add build speed article link

* Add pro tip for pod install alias

* Restructure, repeat less

Favor linking to original setup guide instead of repeating content.

* Note about Expo

* Include command on uninstalling global CLI

* How to learn more

* Remove headers in tabs

They don't work correctly with the righthand TOC.

* Make header more clear

* Use quote block less often

There was way too much yellow.

* Opt for instructions using XCode

Because `xcodebuild clean` already failed me once when XCode GUI clean
worked.

* Fix lint issue

* Improve wording

* Use product name

* Fix line wraps

* Reword based on feedback

* Note use of bundle install

* Pod removal instructions

Also standardize on using yarn scripts from template for commands, it's
a little confusing to see the mix of `npx` and `yarn` once we start
referring to `yarn pod-install`

* Convert quotes to admonitions

* Convert Note: to admonitions

* Feedback: Change admonitions to caution

* PR feedback

* New Architecture landing page (#3072)

* First draft of landing page

* Add migration and backwards compatibility links

* lint fix

* Restructure slightly, leaning more on context from Why a New Architecture

* Don't need md in links

* Suggested rewording

* Rephrase pillar summaries

* [Guide - The New Architecture] Why A New Architecture (#3043)

* [Guide - The New Architecture] Pillars (#3046)

* [Guide - The New Architecture] TurboModules as Native Modules (#3039)

* [Guide - The New Architecture] Fabric Components as Native Components (#3040)

* [FEAT][TNA] Fabric Component Guide (#3132)

* [Feat] Add intro for Fabric Components

* feat: add guide to create a Fabric Component

* Add page on codegen (#3155)

* [FEAT] TurboModules guide (#3168)

* [Feat] Add intro for Fabric Components

* feat: add guide to create a Fabric Component

* Beginning of guide/folder structure

* WIP JS Spec

* specification section

* Configuration

* native code intro

* Must be named Spec

* Best stab at iOS native code, but I don't know how to describe what's going on in the code very well. Extrapolated what I could.

* Android instructions

iOS isn't working for me. Builds, but can't load module.

Writing up Android auto-linking next because the steps I tested did
work.

* Include linking instructions from RNNArch repo

* Add example JavaScript

* native modules link

* Address quick feedback items

* Remove, fix for rebased branch

* fix TM parameter on Android

* Revert to 'Codegen' casing

* Revert folly version change

2021.07.22 is for current version on main

* fix typo

* getTurboModule explainer

* Sentence edits

- Fix acronym bolding
- Change wording to "recommended" because "standard" has other
  connotations of possibly being required
- Parentheses unnecessary, distracting

* Remove TODO for now

Getting inconsistent results here, not sure if this is wrong or not;
removing TODO for now so it doesn't block anything

* ABI rephrase, more in line with new Fabric guide wording

* Explain shared C++ code more

* feat: add guide to create a Fabric Component

* feat: add guide to create a Fabric Component

* package.json description

* Lint fixes

* fix: Move JS constants to reduce changes

* fix: Remove newline

* feat: add required step for Android Codegen

* fix: use the proper links

Co-authored-by: Riccardo Cipolleschi <cipolleschi@fb.com>

* wip: migration guide review (#3200)

Co-authored-by: Lizzi Lindboe <lindboe@users.noreply.github.com>

* fix: Fix typo in the sidebar (#3247)

* Delete ubereats.png (#3246)

Redundant image data

* Fixed pod install instructions (#3243)

* Fixed pod install instructions

Yarn must be run prior to pod install, otherwise pod install fails with "Error: Cannot find module 'mkdirp'"

* yarn start is not necessary anymore

* Refer to rntester readme

* Update android studio screenshot (#3253)

* Adding Android 13 Permissions into PermissionsAndroid (#3254)

* TextInput: Add cursorColor Android prop (#3255)

* Update Android Studio screenshot (Windows) (#3257)

* docs (releases): small refactoring and updating templates (#3256)

* Update documentation for keyboard events on Android (#3259)

https://github.com/facebook/react-native/commit/1e48274223ee647ac4fc2c21822b5240f3c47e4c fixed keyboard events on Android 11+ when an activity has set `android:windowSoftInputMode` to `adjustNothing`. Update the documentation to reflect the change.

* Update to Docusaurus stable release, fix alert admonition styling (#3248)

* Change asks to ask (grammar) (#3262)

* contributing: remove old references (#3263)

* adding accessibilityLabelledBy to documentation (#3249)

* Update references to Expo / Expo CLI (#3267)

* feat(images): Adding iOS Image Cache Limits (#3258)

Co-authored-by: Bartosz Kaszubowski <gosimek@gmail.com>

* feat: update instructions around automatic linking (#3269)

* Follow up from #3267 with minor fixes (#3270)

* nit: fix typo in new architecture docs (#3261)

* fix typo

* fix: typescript example

* fix: lint

* make text optional

* fix(images): move app-transport-security reference (#3271)

* fix(images): move app-transport-security reference

* feat(images): updating link references

* fix(network): change network app transport security reference

* fix(docs): updating versioned docs link reference

* Showcase page refresh (#3235)

Co-authored-by: Lorenzo Sciandra <lorenzo.sciandra@gmail.com>

* fix: moving the Using forwardRef and Using a getter to a lower hierarchy level (#3282)

* Upgrade toast Android example to camelCase (#3283)

* Fix link in Introduction (#3290)

* Fix link in Introduction

* Use new page title (potentially renaming that is a separate discussion)

* fix: push steps in a lower hierarchy level (#3296)

* fix type in the new architecture pillars section (#3297)

* cut 0.70 docs (take 2) (#3295)

* Blog post for 0.70 RN release (#3298)

* Blog post for 0.70 RN release

* Fixes and TOC

* Update my GH handle

* Update my GH handle

* Apply suggestions from code review

Co-authored-by: Riccardo <cipolleschi@fb.com>

* Update @titozzz Twitter handle

* Add example for javaPackageName

* Update commits count

* Minor fixes to the wording

Co-authored-by: Dmytro Rykun <dmitry.rykun@gmail.com>
Co-authored-by: Riccardo <cipolleschi@fb.com>

Co-authored-by: Lorenzo Sciandra <notkelset@kelset.dev>
Co-authored-by: Marcin Kozubek <mkozubek@protonmail.com>
Co-authored-by: Malachi Gruenhagen <68450431+nurse-the-code@users.noreply.github.com>
Co-authored-by: Bartosz Kaszubowski <gosimek@gmail.com>
Co-authored-by: Pushkar Yadav <96358784+pushkarydv@users.noreply.github.com>
Co-authored-by: Muhammad Ovi (Owais) <muhammadowaisnaseem@gmail.com>
Co-authored-by: rj-jones <85085648+rj-jones@users.noreply.github.com>
Co-authored-by: fbmal7 <105675860+fbmal7@users.noreply.github.com>
Co-authored-by: Nicola Corti <corti.nico@gmail.com>
Co-authored-by: neildhar <neildhar@users.noreply.github.com>
Co-authored-by: Lorenzo Sciandra <lsciandra@microsoft.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Yvan Zhu <i@zhuyunfeng.com>
Co-authored-by: Mileta Dulović <dulovicmileta1@gmail.com>
Co-authored-by: Ricky <rickhanlonii@fb.com>
Co-authored-by: Andrew <35735666+meatnordrink@users.noreply.github.com>
Co-authored-by: LeoTM <1881059+leotm@users.noreply.github.com>
Co-authored-by: Nicola Corti <ncor@fb.com>
Co-authored-by: Oskar Kwaśniewski <oskarkwasniewski@icloud.com>
Co-authored-by: Furkan Arabacı <furkanarabaci@hotmail.com>
Co-authored-by: Marek Fořt <marekfort@me.com>
Co-authored-by: Riccardo <riccardo.cipolleschi@gmail.com>
Co-authored-by: Władysław Raczek <wsw.raczek@gmail.com>
Co-authored-by: Luna Wei <luwe@fb.com>
Co-authored-by: Evan Charlton <evancharlton@gmail.com>
Co-authored-by: Tushar Varshney <110495886+tusharvars@users.noreply.github.com>
Co-authored-by: Riccardo <cipolleschi@fb.com>
Co-authored-by: Lizzi Lindboe <lindboe@users.noreply.github.com>
Co-authored-by: Jessej Samuel <1234jessej@gmail.com>
Co-authored-by: Seph Soliman <seph@seph.dk>
Co-authored-by: Kimiyasu Morikawa <mail@alea12.net>
Co-authored-by: Agastya Darma <gedeagas22@gmail.com>
Co-authored-by: Nick Gerleman <nick@nickgerleman.com>
Co-authored-by: denis-tsoi-mox <67885203+denis-tsoi-mox@users.noreply.github.com>
Co-authored-by: fabriziobertoglio1987 <fabrizio.bertoglio@gmail.com>
Co-authored-by: Brent Vatne <brentvatne@gmail.com>
Co-authored-by: Michał Pierzchała <thymikee@gmail.com>
Co-authored-by: nishan (o^▽^o) <nishanbende@gmail.com>
Co-authored-by: Lorenzo Sciandra <lorenzo.sciandra@gmail.com>
Co-authored-by: Lucas Alves <lcsjalves@gmail.com>
Co-authored-by: dan <dan.abramov@gmail.com>
Co-authored-by: Dmytro Rykun <dmitry.rykun@gmail.com>